import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import {ToastContainer} from "react-toastify";
import {LoginProvider} from "@/app/providers/LoginProvider";
import ModalLogin from "@/app/components/ModalLogin";
import Sidebar from "@/app/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kitchen Share",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>

    </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <LoginProvider>
        <div className="flex flex-row" >
            <Sidebar/>
          <div className={"mx-auto w-full"}>
            <Navbar/>
            <ModalLogin/>
            <ToastContainer position="bottom-center" autoClose={3000} />
            {children}
          </div>
        </div>
      </LoginProvider>
      </body>
    </html>
  );
}
